# Collection of R commands that will take the users from a JSON file generated by StreamR and find any new unique users. 
# It appends them to a list stored in a file named "UniqueLondonandAreausers.txt"

options(echo=TRUE)
args <- commandArgs

library(twitteR)
library(streamR)
library(jsonlite)

#Take filename from command line to tell the script which file to open.
tweetsFilename <- args(1)

#Load in the file.
newFrame <- parseTweets(tweetsFilename);

#Remove all the tweets from the states.
newFrame <- newFrame[!newFrame$country=="United States",];

#Collect all the usernames that are contained in the appropriate part of the dataframe.
usernames <- unique(newFrame$screen_name);
collectedNames <- scan("UniqueLondonandAreausers.txt",what=character());
combinedList <- unique(c(collectedNames,usernames));
write(combinedList,file="UniqueLondonandAreausers.txt",append=FALSE)
